# app/services/feed_sources.py
# Quality RSS sources for the PM Intelligence Feed.
# Categories: pm | engineering | strategy | ai
# Add new sources here — FeedService picks them up automatically on next refresh.

FEED_SOURCES = [

    # ── PM & Product ──────────────────────────────────────────────────────────
    {"name": "Lenny's Newsletter",       "url": "https://www.lennysnewsletter.com/feed",                   "category": "pm"},
    {"name": "Product Talk",             "url": "https://www.producttalk.org/feed/",                        "category": "pm"},
    {"name": "Mind the Product",         "url": "https://www.mindtheproduct.com/feed/",                     "category": "pm"},
    {"name": "SVPG",                     "url": "https://svpg.com/feed/",                                   "category": "pm"},
    {"name": "Product Coalition",        "url": "https://medium.com/feed/product-coalition",                "category": "pm"},
    {"name": "Productboard Blog",        "url": "https://www.productboard.com/blog/feed/",                  "category": "pm"},
    {"name": "Intercom Blog",            "url": "https://www.intercom.com/blog/feed",                       "category": "pm"},
    {"name": "Amplitude Blog",           "url": "https://amplitude.com/blog/feed",                          "category": "pm"},
    {"name": "Reforge Blog",             "url": "https://www.reforge.com/blog/rss",                         "category": "pm"},
    {"name": "Product School",           "url": "https://productschool.com/blog/feed/",                     "category": "pm"},
    {"name": "Melissa Perri",            "url": "https://melissaperri.com/feed",                            "category": "pm"},
    {"name": "Aha! Blog",               "url": "https://www.aha.io/blog/feed",                             "category": "pm"},
    {"name": "Figma Blog",              "url": "https://www.figma.com/blog/feed/",                         "category": "pm"},
    {"name": "Miro Blog",               "url": "https://miro.com/blog/feed/",                              "category": "pm"},
    {"name": "Pendo Blog",              "url": "https://www.pendo.io/blog/feed/",                          "category": "pm"},
    {"name": "ProductPlan Blog",        "url": "https://www.productplan.com/blog/feed/",                   "category": "pm"},
    {"name": "Mixpanel Blog",           "url": "https://mixpanel.com/blog/feed/",                          "category": "pm"},
    {"name": "Appcues Blog",            "url": "https://www.appcues.com/blog/rss.xml",                     "category": "pm"},

    # ── Engineering ───────────────────────────────────────────────────────────
    {"name": "Netflix Tech Blog",        "url": "https://netflixtechblog.com/feed",                         "category": "engineering"},
    {"name": "Google Engineering",       "url": "https://engineering.googleblog.com/feeds/posts/default",   "category": "engineering"},
    {"name": "Meta Engineering",         "url": "https://engineering.fb.com/feed/",                         "category": "engineering"},
    {"name": "AWS Blog",                 "url": "https://aws.amazon.com/blogs/aws/feed/",                   "category": "engineering"},
    {"name": "Martin Fowler",            "url": "https://martinfowler.com/feed.atom",                       "category": "engineering"},
    {"name": "The Pragmatic Engineer",   "url": "https://newsletter.pragmaticengineer.com/feed",            "category": "engineering"},
    {"name": "Uber Engineering",         "url": "https://www.uber.com/en-US/blog/engineering/rss/",         "category": "engineering"},
    {"name": "Spotify Engineering",      "url": "https://engineering.atspotify.com/feed/",                  "category": "engineering"},
    {"name": "Airbnb Engineering",       "url": "https://medium.com/feed/airbnb-engineering",               "category": "engineering"},
    {"name": "LinkedIn Engineering",     "url": "https://engineering.linkedin.com/blog.rss",                "category": "engineering"},
    {"name": "Cloudflare Blog",          "url": "https://blog.cloudflare.com/rss/",                         "category": "engineering"},
    {"name": "Stripe Engineering",       "url": "https://stripe.com/blog/engineering/feed/rss",             "category": "engineering"},
    {"name": "GitHub Blog",              "url": "https://github.blog/engineering/feed/",                    "category": "engineering"},
    {"name": "Stack Overflow Blog",      "url": "https://stackoverflow.blog/feed/",                         "category": "engineering"},
    {"name": "DoorDash Engineering",     "url": "https://doordash.engineering/feed/",                       "category": "engineering"},
    {"name": "Shopify Engineering",      "url": "https://shopify.engineering/blog.atom",                    "category": "engineering"},
    {"name": "Dropbox Tech",             "url": "https://dropbox.tech/feed",                                "category": "engineering"},
    {"name": "High Scalability",         "url": "http://feeds.feedburner.com/HighScalability",              "category": "engineering"},
    {"name": "InfoQ",                    "url": "https://www.infoq.com/feed/",                              "category": "engineering"},

    # ── Strategy & Business ───────────────────────────────────────────────────
    {"name": "First Round Review",       "url": "https://review.firstround.com/feed.xml",                   "category": "strategy"},
    {"name": "a16z",                     "url": "https://a16z.com/feed/",                                   "category": "strategy"},
    {"name": "Benedict Evans",           "url": "https://www.ben-evans.com/benedictevans/rss.xml",          "category": "strategy"},
    {"name": "HBR",                      "url": "https://feeds.hbr.org/harvardbusiness",                    "category": "strategy"},
    {"name": "Stratechery",              "url": "https://stratechery.com/feed/",                             "category": "strategy"},
    {"name": "Not Boring",               "url": "https://www.notboring.co/feed",                            "category": "strategy"},
    {"name": "Tomasz Tunguz",            "url": "https://tomtunguz.com/index.xml",                          "category": "strategy"},
    {"name": "Andrew Chen",              "url": "https://andrewchen.com/feed/",                             "category": "strategy"},
    {"name": "Paul Graham Essays",       "url": "http://www.paulgraham.com/rss.html",                       "category": "strategy"},
    {"name": "Y Combinator Blog",        "url": "https://blog.ycombinator.com/feed/",                       "category": "strategy"},
    {"name": "Sequoia Capital",          "url": "https://www.sequoiacap.com/feed/",                         "category": "strategy"},
    {"name": "Greylock",                 "url": "https://greylock.com/greymatter/feed/",                    "category": "strategy"},
    {"name": "The Generalist",           "url": "https://www.readthegeneralist.com/feed",                   "category": "strategy"},
    {"name": "CB Insights",              "url": "https://www.cbinsights.com/research/feed/",                "category": "strategy"},
    {"name": "Fred Wilson (AVC)",        "url": "https://avc.com/feed/",                                    "category": "strategy"},
    {"name": "Bessemer VP",              "url": "https://www.bvp.com/atlas/feed",                           "category": "strategy"},

    # ── AI & Research ─────────────────────────────────────────────────────────
    {"name": "Hugging Face Blog",        "url": "https://huggingface.co/blog/feed.xml",                     "category": "ai"},
    {"name": "OpenAI Blog",              "url": "https://openai.com/blog/rss.xml",                          "category": "ai"},
    {"name": "Google AI Blog",           "url": "https://blog.research.google/feeds/posts/default",         "category": "ai"},
    {"name": "Microsoft Research",       "url": "https://www.microsoft.com/en-us/research/blog/feed/",      "category": "ai"},
    {"name": "The Batch (deeplearning)", "url": "https://www.deeplearning.ai/the-batch/feed/",              "category": "ai"},
    {"name": "Import AI",                "url": "https://jack-clark.net/feed/",                             "category": "ai"},
    {"name": "MIT Technology Review",    "url": "https://www.technologyreview.com/feed/",                   "category": "ai"},
    {"name": "Wired (AI)",               "url": "https://www.wired.com/feed/tag/ai/latest/rss",             "category": "ai"},
    {"name": "VentureBeat AI",           "url": "https://venturebeat.com/ai/feed/",                         "category": "ai"},
    {"name": "The Gradient",             "url": "https://thegradient.pub/rss/",                             "category": "ai"},
    {"name": "Ahead of AI",              "url": "https://magazine.sebastianraschka.com/feed",               "category": "ai"},
    {"name": "Last Week in AI",          "url": "https://lastweekin.ai/feed",                               "category": "ai"},
]
